#!/bin/bash
# To use, store as .git/hooks/pre-push inside your repository and make sure
# it has execute permissions.

# run security/vulnerabilities scanner prior to pushing to repo

cd @PROJECT_SOURCE_DIR@
# Check if we actually have commits to push
commits=`git log @{u}..`
if [ -z "$commits" ]; then
    exit 0
fi

scanner=trivy

echo "==== running vulnerabilities scanner (${scanner}) from $0"
echo "     to accept risks create a .trivyignore file in repo's root"
echo "     See https://github.com/aquasecurity/trivy/blob/main/docs/docs/vulnerability/examples/filter.md#by-vulnerability-ids"
echo

# detect if "trivy" is installed
which ${scanner} > /dev/null
if [[ $? != 0 ]]; then
  echo "to install ${scanner} follow instructions on https://github.com/aquasecurity/trivy/blob/main/docs/getting-started/installation.md#debianubuntu"
  exit 1
fi

# without the --exit-code 1 flag - trivy always exists with 0
${scanner} --exit-code 1 fs --ignore-unfixed .
